const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch({
    channel: 'msedge',
    headless: false
  });
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto('https://www.saucedemo.com/');
  await page.locator('#user-name').fill('standard_user');
  await page.locator('#password').fill('secret_sauce');
  await page.locator('#login-button').click();
  await page.getByText('Administration').click();
  await page.getByText('Manage Users').click();
  await page.getByText('Add User').click();
  await page.getByRole('combobox').click();
  await page.getByRole('combobox').fill('sameeullah');
  await page.getByRole('button', { name: 'Ã—' }).click();
  await page.getByRole('button').nth(2).click();
  await page.getByRole('textbox', { name: 'Search', exact: true }).click();
  await page.getByRole('textbox', { name: 'Search', exact: true }).fill('samee');
  await page.getByText('edit').click();
  await page.locator('div:nth-child(8) > .d-flex > .k-switch > .k-switch-track').click();
  await page.getByText('Clear Cache').click();
  await page.getByText('User Access Report').click();
  await page.getByText('summarizeWorkflow History').click();
  await page.getByText('User Role Action Report').click();
  await page.getByText('File Vault').click();
  await page.getByText('dashboardDashboard').click();
  await page.getByText('IDR - Report').click();
  await page.getByText('BM-Transaction').click();
  await page.getByText('Settings', { exact: true }).click();
  await page.getByText('Master Data Setup').click();
  await page.getByText('Business Units').click();
  await page.getByText('Departments').click();
  await page.getByText('apartmentMaster Entity List').click();
  await page.getByText('Business Units').click();
  await page.getByRole('button', { name: 'ï§ Add' }).click();
  await page.getByRole('button', { name: 'Ã—' }).click();
  await page.getByRole('textbox', { name: 'Business Unit Name *' }).click();
  await page.getByRole('textbox', { name: 'Business Unit Name *' }).fill('dd');
  await page.getByRole('textbox', { name: 'Business Unit Abbreviation' }).click();
  await page.getByRole('textbox', { name: 'Business Unit Abbreviation' }).fill('dd');
  await page.getByRole('textbox', { name: 'IP Owner' }).click();
  await page.getByRole('textbox', { name: 'IP Owner' }).fill('dd');
  await page.getByRole('textbox', { name: 'Description' }).click();
  await page.getByRole('textbox', { name: 'Description' }).fill('dd');
  await page.getByText('Save Cancel question_mark').click();
  await page.getByRole('button', { name: 'Cancel' }).click();
  await page.getByText('Departments').click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByText('Departments').click();
  await page.getByRole('button', { name: 'ï§ Add' }).click();
  await page.getByRole('button', { name: 'Ã—' }).click();
  await page.getByRole('textbox', { name: 'Department *' }).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('button', { name: 'ï‚“ Export/Import' }).click();
  await page.getByRole('button', { name: 'Ã—' }).click();
  await page.getByRole('button', { name: 'Download Template' }).click();
  await page.getByRole('button', { name: 'Ã—' }).click();
  await page.getByRole('button', { name: 'Select files...' }).click();
  await page.getByRole('button', { name: 'Import History' }).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByText('Master Entity List').click();
  await page.getByRole('button', { name: 'ï§ Add' }).click();
  await page.getByRole('button', { name: 'Ã—' }).click();
  await page.getByRole('textbox', { name: 'Entity Code *' }).click();
  await page.getByRole('textbox', { name: 'Entity Name *' }).click();
  await page.locator('.flex-grow-1').first().click();
  await page.getByRole('combobox', { name: 'UPE Indicator *' }).click();
  await page.getByRole('combobox', { name: 'Region' }).click();
  await page.getByRole('combobox', { name: 'Jurisdiction *' }).click();
  await page.getByRole('textbox', { name: 'City' }).click();
  await page.getByRole('combobox', { name: 'Fiscal Month *' }).click();
  await page.getByRole('combobox', { name: 'Fiscal Date *' }).click();
  await page.getByRole('combobox', { name: 'Reporting Currency *' }).click();
  await page.locator('span').filter({ hasText: 'On Off Reporting In Local' }).locator('div').click();
  await page.getByRole('textbox', { name: 'Legal Ownership' }).click();
  await page.getByRole('combobox', { name: 'Functional Profile' }).click();
  await page.getByRole('textbox', { name: 'Registered Office' }).click();
  await page.getByRole('textbox', { name: 'Branches and other Offices of' }).click();
  await page.getByRole('textbox', { name: 'Taxpayer\'s Identification' }).click();
  await page.getByRole('combobox', { name: 'Jurisdiction that issued the' }).click();
  await page.getByRole('button', { name: 'Cancel' }).click();
  await page.getByText('Jurisdiction Region Mappings').click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByText('Jurisdiction Region Mappings').click();
  await page.getByRole('toolbar', { name: 'Grid toolbar' }).click();
  await page.getByRole('button', { name: 'Ã—' }).click();
  await page.getByRole('button', { name: 'ï§ Add' }).click();
  await page.getByRole('textbox', { name: 'Name *' }).click();
  await page.getByRole('spinbutton').click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('button', { name: 'chevron_left' }).click();
  await page.getByText('Jurisdiction Region Mappings').click();
  await page.getByRole('button', { name: 'ï„ Benchmarking Study Region' }).click();
  await page.getByRole('button', { name: 'ï§ Add' }).click();
  await page.getByRole('button', { name: 'Ã—' }).click();
  await page.getByRole('textbox', { name: 'Name *' }).click();
  await page.getByRole('spinbutton').click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByText('Chart of Accounts').click();
  await page.getByRole('button', { name: 'ï§ Add' }).click();
  await page.getByRole('button', { name: 'Ã—' }).click();
  await page.getByRole('textbox', { name: 'Account Name *' }).click();
  await page.getByRole('textbox', { name: 'Account Alias' }).click();
  await page.getByRole('combobox', { name: 'Class *' }).click();
  await page.locator('form div').filter({ hasText: 'Class' }).nth(3).click();
  await page.getByRole('textbox', { name: 'Comments' }).click();
  await page.locator('form div').filter({ hasText: 'Comments' }).nth(3).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('button', { name: 'ï‚“ Export/Import' }).click();
  await page.getByRole('button', { name: 'Ã—' }).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByText('Transaction Types').click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByText('Transaction Types').click();
  await page.getByRole('button', { name: 'Ã—' }).click();
  await page.getByText('Benchmarking Study Types').click();
  await page.getByText('PLI Definitions').click();
  await page.getByText('Export Master Data Setup Data').click();
  await page.getByText('Data Import').click();
  await page.getByText('Projects').click();
  await page.getByText('Scoping').click();
  await page.getByText('Project Entities').click();
  await page.getByText('Project Entities').click();
  await page.getByText('Local File Scoping').click();
  await page.getByText('Transaction Type Scoping').click();
  await page.getByText('query_statsBenchmarking').click();
  await page.getByText('inventoryScoping').click();
  await page.getByText('Workplans').click();
  await page.getByText('summarizeLocal File Workplan').click();
  await page.getByText('point_of_saleTransaction').click();
  await page.getByText('Benchmarking Workplan').click();
  await page.getByText('Users Assignment').click();
  await page.getByText('Report Structure Setup').click();
  await page.getByText('Document Templates').click();
  await page.getByText('Report Structures').click();
  await page.getByText('Components').click();
  await page.getByText('assignment_turned_inFree').click();
  await page.getByText('Content Creation').click();
  await page.getByText('Benchmarking Study Modules').click();
  await page.getByText('Transaction Modules').click();
  await page.getByText('Data Collection').click();
  await page.getByText('Local Files').click();
  await page.getByText('Group Data').click();
  await page.getByText('Report Generation').click();
  await page.getByText('Local Files').click();
  await page.close();

  await context.storageState({ path: '.playwright/auth.json' });
  await context.close();
  await browser.close();
})();
